// frontend/src/components/layout/BuyerLayout.vue
<template>
  <ResponsiveLayout :navItems="navItems" theme="light" />
</template>

<script setup>
import { computed } from 'vue'
import { Home, Store, ShoppingBag, ShoppingCart, User } from 'lucide-vue-next'
import ResponsiveLayout from './ResponsiveLayout.vue'
import { useOrders } from '@/composables/useOrders'
import { useCart } from '@/composables/useCart'

const { orders } = useOrders()
const { totalCartCount } = useCart()

const activeOrdersCount = computed(() => {
  return orders.value.filter(o => ['placed', 'confirmed', 'dispatched', 'in_transit'].includes(o.status)).length
})

const navItems = computed(() => [
  { path: '/buyer', label: 'Dashboard', icon: Home, category: 'OVERVIEW' },
  { path: '/buyer/marketplace', label: 'Marketplace', icon: Store, category: 'PROCUREMENT & MARKETPLACE' },
  { path: '/buyer/cart', label: 'Carts', icon: ShoppingBag, category: 'PROCUREMENT & MARKETPLACE', badge: totalCartCount.value > 0 ? totalCartCount.value : null },
  { path: '/buyer/orders', label: 'Orders', icon: ShoppingCart, category: 'PROCUREMENT & MARKETPLACE', badge: activeOrdersCount.value > 0 ? activeOrdersCount.value : null },
  { path: '/buyer/profile', label: 'Buyer Profile', icon: User, category: 'MY ACCOUNT' },
])
</script>

// frontend/src/components/layout/BuyerLayout.tsx
import React from 'react';
import { Home, Store, ShoppingCart, User as UserIcon } from 'lucide-react';
import { ResponsiveLayout, NavItem } from './ResponsiveLayout';

const buyerNavItems: NavItem[] = [
    { path: '/buyer', label: 'Dashboard', icon: Home },
    { path: '/buyer/marketplace', label: 'Marketplace', icon: Store },
    { path: '/buyer/orders', label: 'Orders', icon: ShoppingCart },
    { path: '/buyer/profile', label: 'Profile', icon: UserIcon },
];

export const BuyerLayout: React.FC = () => {
    return (
        <ResponsiveLayout
            navItems={buyerNavItems}
            theme="light"
        />
    );
};
