// frontend/src/pages/buyer/Checkout.vue
<template>
  <div class="space-y-6 max-w-2xl mx-auto pb-12">
    <!-- Header -->
    <div class="flex items-center justify-between border-b border-[#E2E4E7] pb-3">
      <div class="flex items-center gap-3">
        <router-link to="/buyer/cart" class="p-2 hover:bg-gray-100 rounded-xl text-gray-500 transition-colors">
          <ArrowLeft class="w-5 h-5" />
        </router-link>
        <div>
          <h1 class="text-lg font-black text-[#1E2328]">Procurement Batch Checkout</h1>
          <p class="text-xs text-[#5A6270]">Review selected produce batches & total Chapa Escrow payable</p>
        </div>
      </div>

      <span class="px-2.5 py-1 rounded-full bg-emerald-50 text-[#1E9444] border border-emerald-200 text-[11px] font-bold flex items-center gap-1">
        <ShieldCheck class="w-3.5 h-3.5" /> Chapa Protected
      </span>
    </div>

    <!-- Main Content Container -->
    <div v-if="checkoutItems.length > 0" class="space-y-6">
      
      <!-- Selected Produce Batches List Card -->
      <div class="bg-white border border-[#E2E4E7] rounded-2xl p-5 shadow-2xs space-y-4">
        <div class="flex justify-between items-center border-b border-gray-100 pb-3">
          <span class="text-xs font-black text-[#1E2328] uppercase tracking-wider">
            Selected Produce Batches ({{ checkoutItems.length }})
          </span>
          <router-link to="/buyer/cart" class="text-xs font-bold text-[#0B57D0] hover:underline">
            Edit Cart Items
          </router-link>
        </div>

        <div class="space-y-4 divide-y divide-gray-100">
          <div 
            v-for="item in checkoutItems" 
            :key="item.id || item.listing?.id"
            class="pt-3 first:pt-0 space-y-3"
          >
            <div class="flex items-start gap-3">
              <div class="w-12 h-12 bg-[#F8F9FA] border border-gray-100 rounded-xl flex items-center justify-center text-2xl shrink-0">
                {{ item.listing?.cropEmoji || '🌾' }}
              </div>
              <div class="flex-1 min-w-0">
                <div class="flex items-center gap-2 mb-0.5">
                  <span class="px-2 py-0.5 rounded bg-blue-50 text-[#0B57D0] text-[10px] font-bold">
                    {{ item.listing?.grade || 'Grade 1' }}
                  </span>
                </div>
                <h3 class="text-sm font-bold text-[#1E2328] truncate">{{ item.listing?.cropName }}</h3>
                <p class="text-[11px] text-[#5A6270]">
                  {{ item.listing?.farmer?.name || 'Producer' }} · {{ item.listing?.region || 'Ethiopia' }}
                </p>
              </div>

              <div class="text-right shrink-0">
                <span class="text-xs font-black text-[#1E9444]">
                  {{ formatETB((item.listing?.pricePerKg || 0) * (item.quantityKg || 100)) }}
                </span>
                <span class="text-[10px] text-gray-400 block">
                  {{ formatETB(item.listing?.pricePerKg) }}/kg
                </span>
              </div>
            </div>

            <!-- Quantity Controls per Item -->
            <div class="flex flex-col sm:flex-row sm:items-center justify-between bg-[#F8F9FA] p-3 rounded-xl border border-gray-100 text-xs gap-3">
              <span class="text-gray-500 font-medium">Sourcing Volume:</span>
              <div class="flex items-center gap-2">
                <!-- Minus Button -->
                <button 
                  type="button"
                  @click="updateQty(item, (item.quantityKg || 1) - 1)"
                  :disabled="(item.quantityKg || 1) <= 1"
                  class="w-10 h-10 bg-white hover:bg-gray-100 text-gray-800 border border-gray-300 disabled:opacity-40 rounded-xl font-black text-lg flex items-center justify-center transition-all cursor-pointer disabled:cursor-not-allowed shadow-2xs"
                  title="Decrease volume by 1"
                >
                  -
                </button>

                <!-- Input Box -->
                <input 
                  type="number" 
                  :value="item.quantityKg || 1"
                  @input="updateQty(item, $event.target.value)"
                  min="1"
                  :max="item.listing?.availableQty || 100000"
                  step="1"
                  class="w-20 py-2 bg-white border border-[#E2E4E7] focus:border-[#0B57D0] focus:outline-none font-black text-[#1E2328] text-center rounded-xl text-sm shadow-2xs"
                />

                <!-- Plus Button -->
                <button 
                  type="button"
                  @click="updateQty(item, (item.quantityKg || 1) + 1)"
                  :disabled="(item.quantityKg || 1) >= (item.listing?.availableQty || 100000)"
                  class="w-10 h-10 bg-[#0B57D0]/10 text-[#0B57D0] hover:bg-[#0B57D0] hover:text-white border border-[#0B57D0]/30 disabled:opacity-40 rounded-xl font-black text-lg flex items-center justify-center transition-all cursor-pointer disabled:cursor-not-allowed shadow-2xs"
                  title="Increase volume by 1"
                >
                  +
                </button>

                <!-- Unit Dropdown -->
                <select 
                  :value="item.unit || 'KG'" 
                  @change="handleUnitChange(item, $event.target.value)"
                  class="px-2.5 py-2 bg-white border border-[#E2E4E7] focus:border-[#0B57D0] focus:outline-none font-bold text-[#1E2328] rounded-xl text-xs shadow-2xs cursor-pointer"
                >
                  <option value="KG">KG</option>
                  <option value="Quintals">Quintals (100 KG)</option>
                  <option value="Litres">Litres (L)</option>
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Target Delivery Logistics Hub Selector -->
      <div class="bg-white border border-[#E2E4E7] rounded-2xl p-5 shadow-2xs space-y-2">
        <label class="text-xs font-bold text-[#1E2328]">Target Delivery Hub</label>
        <select 
          v-model="selectedHub" 
          class="w-full px-3.5 py-2.5 bg-[#F8F9FA] border border-[#E2E4E7] rounded-xl text-xs font-semibold text-[#1E2328] focus:border-[#0B57D0] focus:outline-none"
        >
          <option value="" disabled>Select Delivery Destination (Loading...)</option>
          <option v-for="hub in availableHubs" :key="hub.id" :value="hub.id">{{ hub.name }}</option>
        </select>
      </div>

      <!-- Financial Breakdown Box -->
      <div class="bg-white border border-[#E2E4E7] rounded-2xl p-5 shadow-2xs space-y-3">
        <h4 class="text-xs font-bold text-[#1E2328] uppercase border-b border-gray-100 pb-2">Financial Breakdown</h4>

        <div class="space-y-2 text-xs">
          <div 
            v-for="item in checkoutItems" 
            :key="`sum-${item.id || item.listing?.id}`"
            class="flex justify-between text-[#5A6270]"
          >
            <span>{{ item.listing?.cropName }} ({{ (item.quantityKg || 1).toLocaleString() }} {{ item.unit || 'KG' }})</span>
            <span class="font-bold text-[#1E2328]">
              {{ formatETB(getItemSubtotal(item)) }}
            </span>
          </div>

          <div class="flex justify-between text-[#5A6270]">
            <span>Chapa Escrow Fee & Inspection</span>
            <span class="font-bold text-emerald-600">Included</span>
          </div>

          <div class="border-t border-dashed border-gray-200 pt-3 flex justify-between items-center text-sm font-black">
            <span class="text-[#1E2328]">Total Payable ETB</span>
            <span class="text-[#1E9444] text-xl">{{ formatETB(totalPayableETB) }}</span>
          </div>
        </div>
      </div>

      <!-- Chapa Escrow Protection Banner -->
      <p class="text-[11px] text-[#5A6270] flex items-center gap-2 bg-[#EDFAF2] p-3.5 rounded-xl border border-[#C3EFCF]">
        <Lock class="w-4 h-4 text-[#1E9444] shrink-0" />
        <span>Funds locked in Chapa Escrow. Payment released to farmers ONLY after driver delivery PIN handoff.</span>
      </p>

      <!-- Pay Action Button -->
      <button 
        @click="handleCheckout" 
        :disabled="isProcessing || totalPayableETB <= 0"
        class="w-full py-4 rounded-xl bg-[#1E9444] text-white font-bold text-sm shadow-md hover:bg-[#0F5C2A] disabled:opacity-50 flex items-center justify-center gap-2 transition-colors cursor-pointer"
      >
        <Loader2 v-if="isProcessing" class="w-4 h-4 animate-spin" />
        <span v-else class="flex items-center gap-2">
          <Lock class="w-4 h-4" />
          <span>Proceed to Chapa Escrow Payment ({{ formatETB(totalPayableETB) }})</span>
        </span>
      </button>

    </div>

    <!-- Empty State -->
    <div v-else class="text-center py-12 bg-white border border-[#E2E4E7] rounded-2xl p-6 text-[#5A6270] space-y-3">
      <p>No produce batches selected for checkout.</p>
      <router-link to="/buyer/marketplace" class="text-[#0B57D0] font-bold text-xs hover:underline">
        Browse Produce Marketplace
      </router-link>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowLeft, ShieldCheck, Lock, Loader2 } from 'lucide-vue-next'
import { useListings } from '@/composables/useListings'
import { useOrders } from '@/composables/useOrders'
import { useAuth } from '@/composables/useAuth'
import { useCart } from '@/composables/useCart'
import { api } from '@/services/api'
import { formatETB } from '@/utils/helpers'

const route = useRoute()
const router = useRouter()
const { getListingById, listings } = useListings()
const { placeOrder } = useOrders()
const { user } = useAuth()
const { selectedItems, cartItems, updateQuantity, updateUnit, getItemSubtotal, clearCart } = useCart()

const isProcessing = ref(false)
const selectedHub = ref('')
const availableHubs = ref([]) // To be populated by backend

const checkoutItems = computed(() => {
  // 1. If explicit listing ID passed in URL path
  if (route.params.id) {
    const singleListing = getListingById(route.params.id)
    if (singleListing) {
      return [{
        id: `single-${singleListing.id}`,
        listing: singleListing,
        quantityKg: 1,
        unit: 'KG'
      }]
    }
  }

  // 2. Return selected items from cart if any selected
  if (selectedItems.value.length > 0) {
    return selectedItems.value
  }

  // 3. Return all items in cart if none selected
  if (cartItems.value.length > 0) {
    return cartItems.value
  }

  // 4. Default fallback to first active listing
  if (listings.value.length > 0) {
    return [{
      id: `default-${listings.value[0].id}`,
      listing: listings.value[0],
      quantityKg: 1,
      unit: 'KG'
    }]
  }

  return []
})

const updateQty = (item, newQty) => {
  const parsed = parseInt(newQty)
  if (item.id && !item.id.startsWith('single-') && !item.id.startsWith('default-')) {
    updateQuantity(item.id, parsed)
  } else {
    const max = item.listing?.availableQty || 100000
    if (isNaN(parsed) || parsed < 1) {
      item.quantityKg = 1
    } else if (parsed > max) {
      item.quantityKg = max
    } else {
      item.quantityKg = parsed
    }
  }
}

const handleUnitChange = (item, newUnit) => {
  if (item.id && !item.id.startsWith('single-') && !item.id.startsWith('default-')) {
    updateUnit(item.id, newUnit)
  } else {
    item.unit = newUnit
  }
}

const totalPayableETB = computed(() => {
  return checkoutItems.value.reduce((sum, item) => {
    return sum + getItemSubtotal(item)
  }, 0)
})

const handleCheckout = async () => {
  if (checkoutItems.value.length === 0) return
  isProcessing.value = true

  try {
    const firstListing = checkoutItems.value[0]?.listing
    const rawId = firstListing?.id ? String(firstListing.id).replace(/[^0-9]/g, '') : ''
    const cleanListingId = parseInt(rawId) || 2
    const targetQty = checkoutItems.value[0]?.quantityKg || 500

    // 1. Reserve stock & create order on backend
    let orderId = null
    const checkoutRes = await api.checkoutOrder({ 
      listing_id: cleanListingId, 
      quantity_kg: targetQty
    }).catch(() => null)

    if (checkoutRes?.order?.id) {
      orderId = checkoutRes.order.id
    }

    // 2. Sync local order placement state for all items
    checkoutItems.value.forEach(item => {
      if (item.listing) {
        placeOrder(item.listing, user.value, item.quantityKg || 100)
      }
    })

    // 3. Call backend Chapa payment initiation API if real order created
    if (orderId) {
      const payRes = await api.initiateOrderPayment(orderId).catch(() => null)

      // Clear checkout items from cart
      clearCart()

      // 4. Direct redirect to Chapa hosted payment checkout URL (e.g. https://checkout.chapa.co/...)
      if (payRes && payRes.checkout_url) {
        window.location.href = payRes.checkout_url
        return
      }
    }

    // 5. Fallback redirect if backend is offline or mock order used
    alert('Payment Initiation Failed: Make sure the local backend API and Chapa keys are active.')
  } catch (err) {
    alert(err.message || 'Payment initiation failed.')
  } finally {
    isProcessing.value = false
  }
}
</script>

// frontend/src/pages/buyer/Checkout.tsx
import React, { useState } from 'react';
import { useSearchParams, useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, ShieldCheck, CheckCircle2, Lock, ShoppingCart } from 'lucide-react';
import { useListings } from '@/hooks/useListings';
import { useOrders } from '@/hooks/useOrders';
import { useAuth } from '@/hooks/useAuth';
import { formatETB } from '@/lib/utils';
import { Buyer } from '@/types';
import { api } from '@/services/api';

export const Checkout: React.FC = () => {
    const { id } = useParams<{ id: string }>();
    const [searchParams] = useSearchParams();
    const navigate = useNavigate();

    const { listings, getListingById } = useListings();
    const { placeOrder } = useOrders();
    const { user } = useAuth();

    const isBulk = searchParams.get('bulk') === 'true' || id === 'bulk' || !id;

    // Load Cart Item IDs for Bulk Checkout
    const cartItemIds: string[] = (() => {
        const saved = localStorage.getItem('agri_cart_items');
        return saved ? JSON.parse(saved) : ['listing-1', 'listing-3'];
    })();

    // Default quantities for cart items (or params)
    const cartListings = listings.filter((l) => cartItemIds.includes(l.id));

    // Single item fallback
    const singleListing = getListingById(id || '');
    const qtyParam = searchParams.get('qty');
    const singleQuantityKg = qtyParam ? parseInt(qtyParam, 10) : singleListing ? singleListing.minOrderQty : 500;

    const [isProcessing, setIsProcessing] = useState(false);
    const [isSuccess, setIsSuccess] = useState(false);

    // Calculate totals
    let totalAmount = 0;
    let subtotal = 0;

    if (isBulk) {
        subtotal = cartListings.reduce((sum, item) => sum + (item.pricePerKg * (item.minOrderQty || 1000)), 0);
        totalAmount = subtotal;
    } else if (singleListing) {
        subtotal = singleListing.pricePerKg * singleQuantityKg;
        totalAmount = subtotal;
    }

    const handleConfirmPay = async () => {
        setIsProcessing(true);
        try {
            if (isBulk) {
                // Call backend API for bulk cart checkout
                const numCartIds = cartItemIds.map((cId) => parseInt(cId.replace(/\D/g, '')) || 1);
                const res = await api.checkoutOrder({ cart_item_ids: numCartIds });

                if (res?.order?.id) {
                    const payRes = await api.initiateOrderPayment(res.order.id);
                    if (payRes?.checkout_url) {
                        window.location.href = payRes.checkout_url;
                        return;
                    }
                }

                // Local fallback: place orders for all cart items
                cartListings.forEach((item) => {
                    placeOrder(item, user as Buyer, item.minOrderQty || 1000);
                });
                localStorage.removeItem('agri_cart_items');
            } else if (singleListing) {
                // Single item checkout
                const numId = parseInt(singleListing.id.replace(/\D/g, '')) || 1;
                const res = await api.checkoutOrder({ listing_id: numId, quantity_kg: singleQuantityKg });

                if (res?.order?.id) {
                    const payRes = await api.initiateOrderPayment(res.order.id);
                    if (payRes?.checkout_url) {
                        window.location.href = payRes.checkout_url;
                        return;
                    }
                }

                placeOrder(singleListing, user as Buyer, singleQuantityKg);
            }

            setIsProcessing(false);
            setIsSuccess(true);
        } catch (err) {
            console.warn('Fallback to local order simulation:', err);
            if (isBulk) {
                cartListings.forEach((item) => {
                    placeOrder(item, user as Buyer, item.minOrderQty || 1000);
                });
                localStorage.removeItem('agri_cart_items');
            } else if (singleListing) {
                placeOrder(singleListing, user as Buyer, singleQuantityKg);
            }
            setIsProcessing(false);
            setIsSuccess(true);
        }
    };

    if (!isBulk && !singleListing) {
        return (
            <div className="p-8 text-center bg-white rounded-2xl border border-gray-200 my-8">
                <h3 className="text-base font-bold text-gray-800">Produce listing not found</h3>
                <button
                    type="button"
                    onClick={() => navigate('/buyer/marketplace')}
                    className="mt-4 px-4 py-2 bg-[#1E9444] text-white rounded-xl text-xs font-semibold"
                >
                    Back to Produce Marketplace
                </button>
            </div>
        );
    }

    if (isSuccess) {
        return (
            <div className="p-6 text-center space-y-5 my-auto max-w-lg mx-auto">
                <div className="w-16 h-16 rounded-full bg-[#EDFAF2] text-[#1E9444] flex items-center justify-center mx-auto border-2 border-[#1E9444]">
                    <CheckCircle2 className="w-10 h-10 stroke-[2.5]" />
                </div>
                <div>
                    <h2 className="text-xl font-black text-[#1E2328]">Payment Secured in Escrow!</h2>
                    <p className="text-xs text-[#5A6270] mt-1 max-w-xs mx-auto font-medium">
                        Your payment of <strong>{formatETB(totalAmount)}</strong> for {isBulk ? `${cartListings.length} produce batches` : singleListing?.cropName} has been locked in Chapa Escrow.
                    </p>
                </div>

                <div className="bg-[#FFF8EC] border border-[#FFE5A5] rounded-2xl p-4 text-left text-xs space-y-1">
                    <span className="font-bold text-[#D88C0A] flex items-center gap-1">
                        <Lock className="w-3.5 h-3.5" /> Next Steps:
                    </span>
                    <p className="text-[#5A6270]">
                        Track delivery progress on the Orders page. Funds will remain safely locked in escrow until you verify goods receipt with your PIN code.
                    </p>
                </div>

                <button
                    type="button"
                    onClick={() => navigate('/buyer/orders')}
                    className="w-full py-3 rounded-2xl bg-[#1E9444] text-white font-bold text-xs shadow-md hover:bg-[#0F5C2A] transition-colors cursor-pointer"
                >
                    View My Orders
                </button>
            </div>
        );
    }

    return (
        <div className="w-full flex flex-col min-h-full pb-8 max-w-2xl mx-auto space-y-4">
            {/* Top Bar Header */}
            <div className="px-4 py-3 bg-white border-b border-[#E2E4E7] flex items-center gap-3 sticky top-14 z-30 rounded-b-2xl shadow-2xs">
                <button
                    type="button"
                    onClick={() => navigate(-1)}
                    className="w-8 h-8 rounded-full flex items-center justify-center hover:bg-[#F0F1F2] transition-colors cursor-pointer"
                >
                    <ArrowLeft className="w-5 h-5 text-[#1E2328]" />
                </button>
                <div>
                    <h2 className="text-base font-black text-[#1E2328]">
                        {isBulk ? `Bulk Escrow Checkout (${cartListings.length} Produce Batches)` : 'Single Produce Escrow Checkout'}
                    </h2>
                    <p className="text-[11px] text-[#5A6270]">
                        Protected by Chapa Escrow Guarantee
                    </p>
                </div>
            </div>

            <div className="p-2 sm:p-4">
                <div className="bg-white border border-[#E2E4E7] rounded-3xl p-5 shadow-xs space-y-5">

                    {/* Produce Items Summary Breakdown */}
                    {isBulk ? (
                        <div className="space-y-3">
                            <h4 className="text-xs font-black text-[#1E2328] uppercase tracking-wider flex items-center gap-1.5">
                                <ShoppingCart className="w-4 h-4 text-[#1E9444]" />
                                <span>Cart Items Included ({cartListings.length})</span>
                            </h4>

                            <div className="space-y-2 max-h-60 overflow-y-auto pr-1">
                                {cartListings.map((item) => (
                                    <div
                                        key={item.id}
                                        className="flex items-center gap-3 bg-[#F8F9FA] p-3 rounded-2xl border border-gray-200"
                                    >
                                        <span className="text-2xl shrink-0">{item.cropEmoji}</span>
                                        <div className="flex-1 min-w-0">
                                            <h5 className="text-xs font-bold text-[#1E2328] truncate">{item.cropName}</h5>
                                            <p className="text-[11px] text-[#5A6270]">
                                                {(item.minOrderQty || 1000).toLocaleString()} kg @ {formatETB(item.pricePerKg)}/kg
                                            </p>
                                        </div>
                                        <span className="text-xs font-black text-[#1E9444]">
                                            {formatETB(item.pricePerKg * (item.minOrderQty || 1000))}
                                        </span>
                                    </div>
                                ))}
                            </div>
                        </div>
                    ) : (
                        /* Single Item Summary */
                        <div className="flex items-center gap-3 bg-[#F8F9FA] p-3.5 rounded-2xl border border-gray-200">
                            <div className="w-12 h-12 rounded-xl bg-white border border-gray-200 flex items-center justify-center text-2xl shrink-0">
                                {singleListing?.cropEmoji}
                            </div>
                            <div className="flex-1 min-w-0">
                                <h4 className="text-sm font-bold text-[#1E2328] truncate">{singleListing?.cropName}</h4>
                                <p className="text-xs text-[#5A6270]">
                                    {singleQuantityKg.toLocaleString()} kg @ {formatETB(singleListing?.pricePerKg || 0)}/kg
                                </p>
                            </div>
                        </div>
                    )}

                    <hr className="border-[#E2E4E7]" />

                    {/* Total Amount Card */}
                    <div className="text-center py-2 bg-emerald-50/60 rounded-2xl p-4 border border-emerald-100">
                        <span className="text-xs font-bold text-[#5A6270] block uppercase tracking-wider">
                            Total Escrow Payment
                        </span>
                        <span className="text-2xl sm:text-3xl font-black text-[#1E9444] mt-0.5 block leading-tight">
                            {formatETB(totalAmount)}
                        </span>
                    </div>

                    {/* Chapa Payment Option */}
                    <div className="bg-[#F8F9FA] border border-[#E2E4E7] rounded-2xl p-3.5 flex items-center justify-between">
                        <div className="flex items-center gap-3">
                            <div className="w-9 h-9 rounded-xl bg-[#1E9444] text-white flex items-center justify-center font-black text-xl shadow-2xs">
                                C
                            </div>
                            <div>
                                <h5 className="text-xs font-bold text-[#1E2328] leading-tight">Pay via Chapa Escrow</h5>
                                <span className="text-[11px] text-[#5A6270]">Secured Ethiopian B2B Gateway</span>
                            </div>
                        </div>
                        <span className="text-[11px] font-semibold text-[#5A6270]">Telebirr · CBE · Banks</span>
                    </div>

                    {/* Protection Banner */}
                    <div className="bg-[#EDFAF2] border border-[#C3EFCF] rounded-2xl p-3.5 flex items-start gap-2.5">
                        <ShieldCheck className="w-5 h-5 text-[#1E9444] shrink-0 mt-0.5" />
                        <p className="text-xs text-[#0F5C2A] leading-relaxed font-medium">
                            Funds remain 100% protected in escrow. Farmer receives payout only after your delivery PIN verification at destination warehouse.
                        </p>
                    </div>

                    {/* Itemized Breakdown */}
                    <div className="space-y-2 text-xs pt-1">
                        <div className="flex justify-between text-[#5A6270]">
                            <span>Produce Subtotal ({isBulk ? `${cartListings.length} items` : `${singleQuantityKg.toLocaleString()} kg`})</span>
                            <span>{formatETB(subtotal)}</span>
                        </div>
                        <div className="flex justify-between text-[#5A6270]">
                            <span>Platform Escrow Protection</span>
                            <span className="text-[#1E9444] font-bold">Free</span>
                        </div>
                        <div className="flex justify-between font-black text-[#1E2328] text-sm pt-2 border-t border-[#E2E4E7]">
                            <span>Grand Total</span>
                            <span className="text-[#1E9444]">{formatETB(totalAmount)}</span>
                        </div>
                    </div>

                    {/* Confirm Button */}
                    <button
                        type="button"
                        onClick={handleConfirmPay}
                        disabled={isProcessing}
                        className="w-full py-3.5 rounded-2xl bg-[#1E9444] text-white font-black text-xs shadow-md hover:bg-[#0F5C2A] transition-all disabled:opacity-50 cursor-pointer"
                    >
                        {isProcessing ? 'Connecting to Chapa Escrow Gateway…' : `Confirm & Pay ${formatETB(totalAmount)} into Escrow`}
                    </button>
                </div>
            </div>
        </div>
    );
};
