// frontend/src/pages/auth/CapabilityApplication.vue
<template>
  <div class="min-h-screen bg-[#EEF2F6] flex items-center justify-center p-4">
    <div class="w-full max-w-[520px] bg-white border border-[#E2E8F0] rounded-[24px] shadow-xl overflow-hidden relative">
      <!-- Top Color Accent Bar -->
      <div 
        :class="[
          'h-[5px] w-full bg-gradient-to-r',
          hasRejected ? 'from-red-500 via-rose-600 to-amber-500' : 'from-[#0B57D0] via-[#E69500] to-[#1E9444]'
        ]"
      />

      <div class="p-6 md:p-8 space-y-6">
        <!-- Header with Back Button -->
        <div class="flex items-center justify-between border-b border-gray-100 pb-4">
          <div class="flex items-center gap-3">
            <button @click="$router.back()" class="w-9 h-9 rounded-full bg-gray-100 flex items-center justify-center hover:bg-gray-200 text-[#1E2328] transition-colors cursor-pointer">
              <ArrowLeft class="w-5 h-5" />
            </button>
            <div>
              <h1 class="text-[18px] font-black text-[#1E2328] tracking-tight">
                {{ hasRejected ? 'Application Status' : (isComplete || hasPending ? 'Capability Application Status' : 'Apply for New Capability') }}
              </h1>
              <p class="text-[12px] text-[#5A6270]">Upgrade your account capabilities on QMT AgriGate</p>
            </div>
          </div>
        </div>

        <!-- Alert Banner for Errors -->
        <div v-if="submitError" class="bg-red-50 border border-red-200 rounded-2xl p-4 flex items-start gap-3 text-xs text-red-700">
          <AlertCircle class="w-4 h-4 text-red-600 shrink-0 mt-0.5" />
          <div>
            <span class="font-black block">Application Alert</span>
            <span>{{ submitError }}</span>
          </div>
        </div>

        <!-- REJECTED SCREEN (If Admin Rejected the Application) -->
        <div v-if="hasRejected && !isReapplying" class="text-center py-4 space-y-5">
          <div class="w-20 h-20 rounded-full bg-red-50 border-2 border-red-500 text-red-600 flex items-center justify-center shadow-md mx-auto">
            <XCircle class="w-10 h-10 stroke-[2.5]" />
          </div>

          <div class="space-y-2">
            <span class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-black bg-red-100 text-red-700 border border-red-200">
              <span class="w-2 h-2 rounded-full bg-red-600 animate-pulse" />
              <span>Application Rejected by Admin</span>
            </span>

            <h3 class="text-[19px] font-black text-[#1E2328]">Action Required for Capability Upgrade</h3>
            <p class="text-[13px] text-[#5A6270] max-w-md mx-auto leading-relaxed">
              Your application for <strong>{{ capRole === 'farmer' ? 'Farmer Producer' : 'Commercial Buyer' }}</strong> capability was reviewed and rejected by the administration team.
            </p>
          </div>

          <!-- REJECTION REASON CARD -->
          <div class="p-4 bg-red-50/80 border border-red-200 rounded-2xl text-left space-y-2 text-xs shadow-2xs">
            <div class="flex items-center gap-2 text-red-900 font-black">
              <AlertCircle class="w-4.5 h-4.5 text-red-600 shrink-0" />
              <span>Admin Rejection Reason:</span>
            </div>
            <p class="text-red-950 font-bold text-[13px] bg-white p-3 rounded-xl border border-red-200 leading-relaxed italic">
              "{{ rejectionReason }}"
            </p>
            <p class="text-[11px] text-red-700 font-semibold pt-1">
              💡 Please update your information or attach the requested extra documents (PDF, Word, or Excel) to submit a fresh application.
            </p>
          </div>

          <div class="flex flex-col sm:flex-row gap-2.5 pt-2">
            <button 
              @click="startReapplication" 
              class="flex-1 py-3.5 rounded-2xl bg-[#1E9444] hover:bg-[#0F5C2A] text-white font-extrabold text-[14px] shadow-md transition-colors cursor-pointer flex items-center justify-center gap-2"
            >
              <RotateCcw class="w-4 h-4" />
              <span>Re-Apply with Corrected Info</span>
            </button>
            <button 
              @click="goToDashboard" 
              class="py-3.5 px-5 rounded-2xl border border-gray-200 text-gray-700 font-extrabold text-[14px] hover:bg-gray-50 transition-colors cursor-pointer"
            >
              Dashboard
            </button>
          </div>
        </div>

        <!-- APPLICATION FORM (If no pending application & not complete) -->
        <form v-else-if="!isComplete && !hasPending" @submit.prevent="handleSubmit" class="space-y-5">
          <!-- Step 1: Select Capability Type -->
          <div>
            <label class="text-[12px] font-bold text-[#1E2328] block mb-2">Select Capability to Apply For</label>
            <div class="grid grid-cols-2 gap-3 text-xs">
              <!-- Farmer Button -->
              <div 
                @click="capRole = 'farmer'" 
                :class="[
                  'p-3.5 rounded-2xl border-2 cursor-pointer transition-all flex flex-col items-center gap-2 text-center',
                  capRole === 'farmer' ? 'border-[#1E9444] bg-[#EDFAF2] text-[#0F5C2A] font-black shadow-2xs' : 'border-[#E2E8F0] bg-white text-[#5A6270] hover:border-gray-300 font-bold'
                ]"
              >
                <div :class="['w-9 h-9 rounded-xl flex items-center justify-center', capRole === 'farmer' ? 'bg-[#1E9444] text-white' : 'bg-gray-100 text-gray-600']">
                  <Tractor class="w-5 h-5" />
                </div>
                <span>Farmer Producer</span>
              </div>

              <!-- Buyer Button -->
              <div 
                @click="capRole = 'buyer'" 
                :class="[
                  'p-3.5 rounded-2xl border-2 cursor-pointer transition-all flex flex-col items-center gap-2 text-center',
                  capRole === 'buyer' ? 'border-[#0B57D0] bg-[#EEF2F6] text-[#0B57D0] font-black shadow-2xs' : 'border-[#E2E8F0] bg-white text-[#5A6270] hover:border-gray-300 font-bold'
                ]"
              >
                <div :class="['w-9 h-9 rounded-xl flex items-center justify-center', capRole === 'buyer' ? 'bg-[#0B57D0] text-white' : 'bg-gray-100 text-gray-600']">
                  <ShoppingBag class="w-5 h-5" />
                </div>
                <span>Commercial Buyer</span>
              </div>
            </div>
          </div>

          <!-- Step 2: Capability Form Fields -->
          <div class="pt-2 border-t border-gray-100 space-y-4">
            <!-- FARMER FORM FIELDS -->
            <template v-if="capRole === 'farmer'">
              <div>
                <label class="text-[12px] font-extrabold text-[#1E2328] block mb-1">Farm Size (in Hectares)</label>
                <input 
                  type="number" 
                  required 
                  min="0.5" 
                  step="0.5"
                  v-model.number="farmSize" 
                  placeholder="e.g. 12.5" 
                  class="w-full px-3.5 py-2.5 bg-[#F0F3F7] border border-transparent rounded-xl text-[14px] font-bold text-[#1E2328] focus:outline-none focus:bg-white focus:border-[#1E9444] transition-all" 
                />
              </div>

              <div>
                <label class="text-[12px] font-extrabold text-[#1E2328] block mb-1">Primary Crops Produced</label>
                <input 
                  type="text" 
                  required 
                  v-model="primaryCrops" 
                  placeholder="e.g. Sidama Coffee, White Teff, Sesame" 
                  class="w-full px-3.5 py-2.5 bg-[#F0F3F7] border border-transparent rounded-xl text-[14px] font-bold text-[#1E2328] focus:outline-none focus:bg-white focus:border-[#1E9444] transition-all" 
                />
              </div>

              <div>
                <label class="text-[12px] font-extrabold text-[#1E2328] block mb-1">Farming Region / Union Location</label>
                <select v-model="region" class="w-full px-3.5 py-2.5 bg-[#F0F3F7] border border-transparent rounded-xl text-[14px] font-bold text-[#1E2328] focus:outline-none focus:bg-white focus:border-[#1E9444] transition-all">
                  <option value="SNNPR">Sidama / SNNPR</option>
                  <option value="Oromia">Oromia</option>
                  <option value="Amhara">Amhara</option>
                  <option value="Tigray">Tigray</option>
                  <option value="Somali">Somali</option>
                  <option value="Afar">Afar</option>
                  <option value="Benishangul">Benishangul-Gumuz</option>
                  <option value="Gambela">Gambela</option>
                  <option value="Addis Ababa">Addis Ababa</option>
                </select>
              </div>

              <div>
                <label class="text-[12px] font-extrabold text-[#1E2328] block mb-1">Co-op Union / Farm Name (Optional)</label>
                <input 
                  type="text" 
                  v-model="unionName" 
                  placeholder="e.g. Sidama Coffee Farmers Cooperative Union" 
                  class="w-full px-3.5 py-2.5 bg-[#F0F3F7] border border-transparent rounded-xl text-[14px] font-bold text-[#1E2328] focus:outline-none focus:bg-white focus:border-[#1E9444] transition-all" 
                />
              </div>

              <!-- EXTRA DOCUMENT UPLOAD FIELD FOR FARMER -->
              <div class="pt-2 border-t border-gray-100">
                <label class="text-[12px] font-extrabold text-[#1E2328] block mb-1 flex items-center justify-between">
                  <span>Attach Supporting Document (Optional)</span>
                  <span class="text-[11px] font-bold text-[#1E9444]">PDF, Word, or Excel</span>
                </label>
                
                <input 
                  type="file" 
                  ref="fileInput" 
                  accept=".pdf,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg" 
                  class="hidden" 
                  @change="handleFileSelect" 
                />

                <div v-if="!attachedDocName" 
                  @click="triggerFileSelect"
                  class="border-2 border-dashed border-gray-200 hover:border-[#1E9444] rounded-2xl p-4 text-center cursor-pointer transition-colors bg-[#F8F9FA] hover:bg-[#EDFAF2]"
                >
                  <Upload class="w-6 h-6 text-[#1E9444] mx-auto mb-1.5" />
                  <span class="text-[12px] font-extrabold text-[#1E9444] block">Click to attach Land Certificate, Kebele ID, or Registry file</span>
                  <span class="text-[10px] text-gray-500 font-medium">Supports PDF, Word (.doc/.docx), Excel (.xls/.xlsx) — Max 15MB</span>
                </div>

                <div v-else class="p-3 bg-[#EDFAF2] border border-[#C3EFCF] rounded-2xl flex items-center justify-between text-xs">
                  <div class="flex items-center gap-2.5 text-[#0F5C2A] font-bold truncate">
                    <FileText class="w-4 h-4 text-[#1E9444] shrink-0" />
                    <span class="truncate">{{ attachedDocName }}</span>
                  </div>
                  <button type="button" @click="removeAttachedDoc" class="p-1 text-red-500 hover:text-red-700 font-bold text-sm">
                    <X class="w-4 h-4" />
                  </button>
                </div>
              </div>
            </template>

            <!-- BUYER FORM FIELDS -->
            <template v-else>
              <div>
                <label class="text-[12px] font-extrabold text-[#1E2328] block mb-1">Company / Business Name</label>
                <input 
                  type="text" 
                  required 
                  v-model="companyName" 
                  placeholder="e.g. Addis Grain Processing Co." 
                  class="w-full px-3.5 py-2.5 bg-[#F0F3F7] border border-transparent rounded-xl text-[14px] font-bold text-[#1E2328] focus:outline-none focus:bg-white focus:border-[#0B57D0] transition-all" 
                />
              </div>

              <div>
                <label class="text-[12px] font-extrabold text-[#1E2328] block mb-1">Business Type</label>
                <select v-model="businessType" class="w-full px-3.5 py-2.5 bg-[#F0F3F7] border border-transparent rounded-xl text-[14px] font-bold text-[#1E2328] focus:outline-none focus:bg-white focus:border-[#0B57D0] transition-all">
                  <option value="exporter">Agricultural Exporter</option>
                  <option value="processor">Food Processor / Mill</option>
                  <option value="wholesaler">Bulk Wholesaler</option>
                  <option value="supermarket">Supermarket Chain</option>
                  <option value="hotel">Hotel / Restaurant Group</option>
                  <option value="distributor">Regional Distributor</option>
                </select>
              </div>

              <div>
                <label class="text-[12px] font-extrabold text-[#1E2328] block mb-1">Tax Identification Number (TIN)</label>
                <input 
                  type="text" 
                  v-model="tinNumber" 
                  placeholder="e.g. 0098765432" 
                  class="w-full px-3.5 py-2.5 bg-[#F0F3F7] border border-transparent rounded-xl text-[14px] font-mono font-bold text-[#1E2328] focus:outline-none focus:bg-white focus:border-[#0B57D0] transition-all" 
                />
              </div>

              <div>
                <label class="text-[12px] font-extrabold text-[#1E2328] block mb-1">Operating Region / City</label>
                <select v-model="region" class="w-full px-3.5 py-2.5 bg-[#F0F3F7] border border-transparent rounded-xl text-[14px] font-bold text-[#1E2328] focus:outline-none focus:bg-white focus:border-[#0B57D0] transition-all">
                  <option value="Addis Ababa">Addis Ababa</option>
                  <option value="Oromia">Oromia</option>
                  <option value="Amhara">Amhara</option>
                  <option value="SNNPR">Sidama / SNNPR</option>
                  <option value="Dire Dawa">Dire Dawa</option>
                  <option value="Tigray">Tigray</option>
                </select>
              </div>

              <!-- EXTRA DOCUMENT UPLOAD FIELD FOR BUYER -->
              <div class="pt-2 border-t border-gray-100">
                <label class="text-[12px] font-extrabold text-[#1E2328] block mb-1 flex items-center justify-between">
                  <span>Attach Business License / Document (Optional)</span>
                  <span class="text-[11px] font-bold text-[#0B57D0]">PDF, Word, or Excel</span>
                </label>
                
                <input 
                  type="file" 
                  ref="fileInput" 
                  accept=".pdf,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg" 
                  class="hidden" 
                  @change="handleFileSelect" 
                />

                <div v-if="!attachedDocName" 
                  @click="triggerFileSelect"
                  class="border-2 border-dashed border-gray-200 hover:border-[#0B57D0] rounded-2xl p-4 text-center cursor-pointer transition-colors bg-[#F8F9FA] hover:bg-[#EEF2F6]"
                >
                  <Upload class="w-6 h-6 text-[#0B57D0] mx-auto mb-1.5" />
                  <span class="text-[12px] font-extrabold text-[#0B57D0] block">Click to attach Trade License or Registration file</span>
                  <span class="text-[10px] text-gray-500 font-medium">Supports PDF, Word (.doc/.docx), Excel (.xls/.xlsx) — Max 15MB</span>
                </div>

                <div v-else class="p-3 bg-[#EEF2F6] border border-blue-200 rounded-2xl flex items-center justify-between text-xs">
                  <div class="flex items-center gap-2.5 text-[#0B57D0] font-bold truncate">
                    <FileText class="w-4 h-4 text-[#0B57D0] shrink-0" />
                    <span class="truncate">{{ attachedDocName }}</span>
                  </div>
                  <button type="button" @click="removeAttachedDoc" class="p-1 text-red-500 hover:text-red-700 font-bold text-sm">
                    <X class="w-4 h-4" />
                  </button>
                </div>
              </div>
            </template>
          </div>

          <!-- Submit Button -->
          <button 
            type="submit" 
            :disabled="isSubmitting" 
            :class="[
              'w-full py-3.5 rounded-2xl text-white font-extrabold text-[15px] shadow-md transition-all flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50',
              capRole === 'farmer' ? 'bg-[#1E9444] hover:bg-[#0F5C2A]' : 'bg-[#0B57D0] hover:bg-[#0842A0]'
            ]"
          >
            <Loader2 v-if="isSubmitting" class="w-4 h-4 animate-spin" />
            <span>Submit {{ capRole === 'farmer' ? 'Farmer Producer' : 'Commercial Buyer' }} Application</span>
          </button>
        </form>

        <!-- PENDING ADMIN APPROVAL SCREEN -->
        <div v-else class="text-center py-4 space-y-5">
          <div class="relative w-20 h-20 mx-auto flex items-center justify-center">
            <div class="absolute inset-0 bg-amber-100 rounded-full animate-ping opacity-25" />
            <div class="w-20 h-20 rounded-full bg-amber-50 border-2 border-[#E69500] text-[#E69500] flex items-center justify-center shadow-md relative z-10">
              <Clock class="w-10 h-10 stroke-[2.5]" />
            </div>
          </div>

          <div class="space-y-2">
            <span class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-black bg-amber-100 text-[#E69500] border border-amber-200">
              <span class="w-2 h-2 rounded-full bg-[#E69500] animate-pulse" />
              <span>Application Pending Admin Approval</span>
            </span>

            <h3 class="text-[19px] font-black text-[#1E2328]">Wait for Administrator Review</h3>
            <p class="text-[13px] text-[#5A6270] max-w-md mx-auto leading-relaxed">
              Your application for <strong>{{ capRole === 'farmer' ? 'Farmer Producer' : 'Commercial Buyer' }}</strong> capability has been submitted and is currently awaiting admin verification.
            </p>
          </div>

          <div class="p-4 bg-[#FFFBEB] border border-amber-200 rounded-2xl text-left space-y-2 text-xs">
            <div class="flex items-center gap-2 text-amber-900 font-extrabold">
              <ShieldCheck class="w-4 h-4 text-[#E69500]" />
              <span>What happens next?</span>
            </div>
            <ul class="space-y-1 text-amber-950 font-medium text-[11px] list-disc list-inside leading-normal">
              <li>Our platform administration team reviews your capability details.</li>
              <li>Please wait for administrator approval before accessing role-specific pages.</li>
              <li>Once approved, full access to the capability dashboard and features will automatically be granted.</li>
            </ul>
          </div>

          <button 
            @click="goToDashboard" 
            class="w-full py-3.5 rounded-2xl bg-[#0B57D0] hover:bg-[#0842A0] text-white font-extrabold text-[14px] shadow-md transition-colors cursor-pointer"
          >
            Return to Dashboard
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { 
  ArrowLeft, ShieldCheck, AlertCircle, Loader2, Tractor, 
  ShoppingBag, Clock, XCircle, RotateCcw, Upload, FileText, X 
} from 'lucide-vue-next'
import { api } from '@/services/api'
import { useAuth } from '@/composables/useAuth'

const router = useRouter()
const { user, isAuthenticated } = useAuth()

const capRole = ref(user.value?.role === 'buyer' ? 'farmer' : 'buyer')
const farmSize = ref(10)
const primaryCrops = ref('Coffee, Teff, Sesame')
const unionName = ref('')

const companyName = ref('')
const businessType = ref('wholesaler')
const tinNumber = ref('')
const region = ref('Addis Ababa')

const fileInput = ref(null)
const attachedDoc = ref(null)
const attachedDocName = ref('')

const isSubmitting = ref(false)
const isComplete = ref(false)
const hasPending = ref(false)
const hasRejected = ref(false)
const isReapplying = ref(false)
const rejectionReason = ref('')
const submitError = ref(null)

const triggerFileSelect = () => {
  if (fileInput.value) fileInput.value.click()
}

const handleFileSelect = (e) => {
  const file = e.target.files?.[0]
  if (file) {
    attachedDoc.value = file
    attachedDocName.value = file.name
  }
}

const removeAttachedDoc = () => {
  attachedDoc.value = null
  attachedDocName.value = ''
  if (fileInput.value) fileInput.value.value = ''
}

onMounted(async () => {
  if (isAuthenticated.value) {
    try {
      const res = await api.fetchMyCapabilityApplications()
      const apps = Array.isArray(res) ? res : (res?.applications || [])
      if (apps.length > 0) {
        const latestApp = apps[0]
        capRole.value = latestApp.capability_type || latestApp.capabilityType || 'farmer'
        
        if (latestApp.status === 'pending') {
          hasPending.value = true
          isComplete.value = true
        } else if (latestApp.status === 'rejected') {
          hasRejected.value = true
          rejectionReason.value = latestApp.rejection_reason || latestApp.rejectionReason || 'The application details provided could not be verified by administration.'
          isComplete.value = true
        }
      }
    } catch {
      // offline fallback
    }
  }
})

const startReapplication = () => {
  isReapplying.value = true
  hasRejected.value = false
  hasPending.value = false
  isComplete.value = false
}

const handleSubmit = async () => {
  submitError.value = null

  if (!isAuthenticated.value) {
    router.push('/login')
    return
  }

  isSubmitting.value = true

  try {
    const docs = attachedDocName.value ? [attachedDocName.value] : []
    
    const payload = {
      capability_type: capRole.value,
      supporting_documents: docs,
      application_data: capRole.value === 'farmer' ? {
        farm_size: farmSize.value,
        primary_crops: primaryCrops.value,
        region: region.value,
        union_name: unionName.value,
      } : {
        company_name: companyName.value,
        business_type: businessType.value,
        tin_number: tinNumber.value,
        region: region.value,
      }
    }

    await api.submitCapabilityApplication(payload)
    isSubmitting.value = false
    isComplete.value = true
    hasPending.value = true
    hasRejected.value = false
    isReapplying.value = false
  } catch (err) {
    isSubmitting.value = false
    submitError.value = err.message || 'Failed to submit capability application. Please try again.'
  }
}

const goToDashboard = () => {
  if (user.value?.role === 'farmer') router.push('/farmer')
  else if (user.value?.role === 'admin') router.push('/admin')
  else router.push('/buyer')
}
</script>

// frontend/src/pages/auth/CapabilityApplication.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Upload, FileText, ArrowLeft, ShieldCheck, AlertCircle, Loader2 } from 'lucide-react';
import { api } from '@/services/api';
import { useAuth } from '@/hooks/useAuth';

export const CapabilityApplication: React.FC = () => {
    const navigate = useNavigate();
    const { user, isAuthenticated } = useAuth();
    const [role, setRole] = useState<'farmer' | 'buyer'>('farmer');
    const [uploadedFiles, setUploadedFiles] = useState<string[]>([]);
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [isComplete, setIsComplete] = useState(false);
    const [submitError, setSubmitError] = useState<string | null>(null);

    const handleUpload = () => {
        const docName = role === 'farmer'
            ? `land_certificate_${Date.now().toString().slice(-4)}.pdf`
            : `business_license_${Date.now().toString().slice(-4)}.pdf`;
        setUploadedFiles((prev) => [...prev, docName]);
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setSubmitError(null);

        if (!isAuthenticated) {
            navigate('/login');
            return;
        }

        if (uploadedFiles.length === 0) {
            setSubmitError('Please attach at least one supporting verification document.');
            return;
        }

        setIsSubmitting(true);

        try {
            await api.submitCapabilityApplication({
                capability_type: role,
                supporting_documents: uploadedFiles,
            });
            setIsSubmitting(false);
            setIsComplete(true);
        } catch (err: any) {
            setIsSubmitting(false);
            setSubmitError(err.message || 'Failed to submit application. You may already have an active capability or pending application.');
        }
    };

    return (
        <div className="min-h-screen bg-[#F8F9FA] flex items-center justify-center p-4">
            <div className="w-full max-w-[480px] bg-white border border-[#E2E4E7] rounded-2xl p-6 shadow-md space-y-6">
                <div className="flex items-center gap-3">
                    <button
                        onClick={() => navigate(-1)}
                        className="w-8 h-8 rounded-full flex items-center justify-center hover:bg-[#F0F1F2]"
                    >
                        <ArrowLeft className="w-5 h-5 text-[#1E2328]" />
                    </button>
                    <div>
                        <h2 className="text-[18px] font-bold text-[#1E2328]">Capability Application</h2>
                        <p className="text-[12px] text-[#5A6270]">Legal document verification upload & role upgrade</p>
                    </div>
                </div>

                {submitError && (
                    <div className="bg-red-50 border border-red-200 rounded-xl p-3.5 flex items-start gap-2.5 text-xs text-red-700">
                        <AlertCircle className="w-4 h-4 text-red-600 shrink-0 mt-0.5" />
                        <div>
                            <span className="font-bold block">Application Alert</span>
                            <span>{submitError}</span>
                        </div>
                    </div>
                )}

                {!isComplete ? (
                    <form onSubmit={handleSubmit} className="space-y-5">
                        <div>
                            <label className="text-[12px] font-bold text-[#1E2328] block mb-1.5">
                                Applying for Capability
                            </label>
                            <div className="grid grid-cols-2 gap-2 text-[13px] font-bold">
                                <button
                                    type="button"
                                    onClick={() => setRole('farmer')}
                                    className={`py-2.5 rounded-xl border transition-all ${role === 'farmer'
                                        ? 'bg-[#EDFAF2] border-[#1E9444] text-[#1E9444]'
                                        : 'bg-white border-[#E2E4E7] text-[#5A6270]'
                                        }`}
                                >
                                    Farmer Producer
                                </button>
                                <button
                                    type="button"
                                    onClick={() => setRole('buyer')}
                                    className={`py-2.5 rounded-xl border transition-all ${role === 'buyer'
                                        ? 'bg-[#EDFAF2] border-[#1E9444] text-[#1E9444]'
                                        : 'bg-white border-[#E2E4E7] text-[#5A6270]'
                                        }`}
                                >
                                    Commercial Buyer
                                </button>
                            </div>
                        </div>

                        <div>
                            <label className="text-[12px] font-bold text-[#1E2328] block mb-1.5">
                                {role === 'farmer'
                                    ? 'Land Ownership Certificate / Kebele ID'
                                    : 'Trade License / TIN Registration Certificate'}
                            </label>

                            <div
                                onClick={handleUpload}
                                className="border-2 border-dashed border-[#E2E4E7] rounded-xl p-6 text-center cursor-pointer hover:border-[#1E9444] transition-colors bg-[#F8F9FA]"
                            >
                                <Upload className="w-8 h-8 text-[#1E9444] mx-auto mb-2" />
                                <span className="text-[13px] font-bold text-[#1E9444] block">
                                    Tap to attach document (PDF, PNG, JPG)
                                </span>
                                <span className="text-[11px] text-[#5A6270]">Max file size 15MB</span>
                            </div>
                        </div>

                        {uploadedFiles.length > 0 && (
                            <div className="space-y-2">
                                <span className="text-[12px] font-bold text-[#1E2328]">Uploaded Documents:</span>
                                {uploadedFiles.map((file, i) => (
                                    <div
                                        key={i}
                                        className="p-3 bg-[#EDFAF2] border border-[#C3EFCF] rounded-xl flex items-center justify-between text-[12px]"
                                    >
                                        <div className="flex items-center gap-2 text-[#0F5C2A] font-bold">
                                            <FileText className="w-4 h-4" />
                                            <span>{file}</span>
                                        </div>
                                        <span className="text-[#1E9444] font-bold">Attached</span>
                                    </div>
                                ))}
                            </div>
                        )}

                        <button
                            type="submit"
                            disabled={uploadedFiles.length === 0 || isSubmitting}
                            className="w-full py-3.5 rounded-full bg-[#1E9444] text-white font-bold text-[15px] shadow-md hover:bg-[#0F5C2A] disabled:opacity-50 btn-hover flex items-center justify-center gap-2"
                        >
                            {isSubmitting ? (
                                <>
                                    <Loader2 className="w-4 h-4 animate-spin" />
                                    <span>Submitting Application to REST API...</span>
                                </>
                            ) : (
                                <span>Submit Verification Application</span>
                            )}
                        </button>
                    </form>
                ) : (
                    <div className="text-center py-6 space-y-4">
                        <div className="w-14 h-14 rounded-full bg-[#EDFAF2] text-[#1E9444] flex items-center justify-center mx-auto border-2 border-[#1E9444]">
                            <ShieldCheck className="w-8 h-8 stroke-[2.5]" />
                        </div>
                        <h3 className="text-[18px] font-bold text-[#1E2328]">Application Submitted!</h3>
                        <p className="text-[13px] text-[#5A6270]">
                            Your request for <strong>{role === 'farmer' ? 'Farmer Producer' : 'Commercial Buyer'}</strong> capability has been submitted to our moderation queue. You will receive authorization once approved by an admin.
                        </p>
                        <button
                            onClick={() => navigate(user?.role === 'farmer' ? '/farmer' : '/buyer')}
                            className="w-full py-3 rounded-full bg-[#1E9444] text-white font-bold text-[14px]"
                        >
                            Return to Dashboard
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
};
