// frontend/src/pages/farmer/FarmerProfile.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
    ArrowLeft,
    Camera,
    CheckCircle2,
    ArrowLeftRight,
    X,
    Phone,
    BadgeCheck,
    Edit3,
    Check,
    Shield,
    User,
    Building2,
    Calendar,
    TrendingUp,
    Globe,
    Award,
    CreditCard,
    Sprout
} from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';
import { Farmer } from '@/types';
import { api, getAuthToken } from '@/services/api';

export const FarmerProfile: React.FC = () => {
    const navigate = useNavigate();
    const { user, switchRole, hasBuyerCapability } = useAuth();
    const farmer = user as Farmer;

    // Display Identity State
    const [fullName, setFullName] = useState(farmer?.name || 'Aymen Farmer');
    const [farmName, setFarmName] = useState('Hawassa Green Agri Co-Op');
    const [phone, setPhone] = useState(farmer?.phone || '+251 918 280 155');
    const [region, setRegion] = useState('Sidama Region, Hawassa, Ethiopia');

    // Bank Account & Payout State
    const [paymentProvider, setPaymentProvider] = useState('Commercial Bank of Ethiopia (CBE)');
    const [accountName, setAccountName] = useState(fullName);
    const [accountNumber, setAccountNumber] = useState('1000189281928');
    const [bankBranch, setBankBranch] = useState('Hawassa Main Branch');

    // Modal Edit State
    const [isEditModalOpen, setIsEditModalOpen] = useState(false);
    const [modalFullName, setModalFullName] = useState(fullName);
    const [modalFarmName, setModalFarmName] = useState(farmName);
    const [modalPhone, setModalPhone] = useState(phone);
    const [modalRegion, setModalRegion] = useState(region);
    const [modalProvider, setModalProvider] = useState(paymentProvider);
    const [modalAccountName, setModalAccountName] = useState(accountName);
    const [modalAccountNumber, setModalAccountNumber] = useState(accountNumber);
    const [modalBankBranch, setModalBankBranch] = useState(bankBranch);

    // Toast Notice
    const [toastMsg, setToastMsg] = useState('');
    const [isSubmitting, setIsSubmitting] = useState(false);

    const openEditModal = () => {
        setModalFullName(fullName);
        setModalFarmName(farmName);
        setModalPhone(phone);
        setModalRegion(region);
        setModalProvider(paymentProvider);
        setModalAccountName(accountName);
        setModalAccountNumber(accountNumber);
        setModalBankBranch(bankBranch);
        setIsEditModalOpen(true);
    };

    const handleFormSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setIsSubmitting(true);

        const token = getAuthToken();
        if (token) {
            try {
                await api.updateProfile({
                    first_name: modalFullName.split(' ')[0] || 'Farmer',
                    second_name: modalFullName.split(' ').slice(1).join(' ') || '',
                    phone: modalPhone,
                    bank_name: modalProvider,
                    account_name: modalAccountName,
                    account_number: modalAccountNumber,
                });
            } catch (err: any) {
                console.warn('Backend update notice:', err.message);
            }
        }

        setFullName(modalFullName);
        setFarmName(modalFarmName);
        setPhone(modalPhone);
        setRegion(modalRegion);
        setPaymentProvider(modalProvider);
        setAccountName(modalAccountName);
        setAccountNumber(modalAccountNumber);
        setBankBranch(modalBankBranch);
        setIsSubmitting(false);
        setIsEditModalOpen(false);

        setToastMsg('Farmer profile details updated successfully');
        setTimeout(() => setToastMsg(''), 3000);
    };

    const getInitials = (nameStr: string) => {
        const parts = nameStr.trim().split(' ');
        if (parts.length >= 2) {
            return (parts[0][0] + parts[1][0]).toUpperCase();
        }
        return (nameStr[0] || 'F').toUpperCase();
    };

    return (
        <div className="w-full min-h-screen bg-[#F0F2F5] text-[#1E2328] font-sans pb-20 animate-fade-in -mx-4 -mt-6 sm:-mx-6 sm:-mt-8 p-4 sm:p-6 max-w-4xl mx-auto">

            {/* LIGHT TOP HEADER BAR */}
            <div className="sticky top-0 z-30 bg-white border-b border-gray-200 px-4 py-3 flex items-center justify-between rounded-t-3xl shadow-xs">
                <div className="flex items-center gap-3">
                    <button
                        type="button"
                        onClick={() => navigate('/farmer')}
                        className="p-2 rounded-full hover:bg-gray-100 text-gray-600 hover:text-gray-900 transition-colors cursor-pointer"
                        title="Back"
                    >
                        <ArrowLeft className="w-5 h-5" />
                    </button>
                    <div>
                        <h2 className="text-sm font-black text-[#1E2328] tracking-wide">Farmer Profile</h2>
                        <span className="text-[11px] text-[#1E9444] font-bold flex items-center gap-1">
                            <span className="w-1.5 h-1.5 rounded-full bg-[#1E9444] animate-pulse" />
                            online • Verified Producer
                        </span>
                    </div>
                </div>

                <div className="flex items-center gap-2">
                    {hasBuyerCapability && (
                        <button
                            type="button"
                            onClick={() => switchRole('buyer')}
                            className="px-3 py-1.5 rounded-xl bg-blue-50 hover:bg-blue-100 text-[#0B57D0] border border-blue-200 text-xs font-extrabold transition-colors cursor-pointer flex items-center gap-1.5"
                        >
                            <ArrowLeftRight className="w-3.5 h-3.5" />
                            <span>Buyer Mode</span>
                        </button>
                    )}

                    <button
                        type="button"
                        onClick={openEditModal}
                        className="p-2 rounded-full hover:bg-gray-100 text-[#1E9444] transition-colors cursor-pointer"
                        title="Edit Profile"
                    >
                        <Edit3 className="w-5 h-5" />
                    </button>
                </div>
            </div>

            {/* LIGHT TOAST NOTICE */}
            {toastMsg && (
                <div className="mt-3 px-4 py-2.5 bg-emerald-50 text-emerald-900 rounded-2xl text-xs font-bold flex items-center gap-2 shadow-xs border border-emerald-200 animate-fade-in">
                    <Check className="w-4 h-4 text-[#1E9444]" />
                    <span>{toastMsg}</span>
                </div>
            )}

            {/* LIGHT PROFILE HERO (AVATAR & MAIN TITLE) */}
            <div className="bg-white rounded-b-3xl p-6 sm:p-8 flex flex-col items-center text-center relative border-b border-gray-200 shadow-xs space-y-3">
                <div className="relative group">
                    {/* Circular Avatar */}
                    <div className="w-24 h-24 sm:w-28 sm:h-28 rounded-full bg-gradient-to-tr from-[#1E9444] via-emerald-600 to-[#D88C0A] p-1 shadow-md">
                        <div className="w-full h-full rounded-full bg-[#062E15] flex items-center justify-center text-white text-3xl font-black tracking-wider">
                            {getInitials(fullName)}
                        </div>
                    </div>

                    <button
                        type="button"
                        onClick={() => alert('Change profile photo')}
                        className="absolute bottom-0 right-0 w-8 h-8 rounded-full bg-[#1E9444] hover:bg-[#0F5C2A] text-white flex items-center justify-center border-2 border-white shadow-md transition-transform hover:scale-110 cursor-pointer"
                        title="Change Photo"
                    >
                        <Camera className="w-4 h-4" />
                    </button>
                </div>

                <div>
                    <div className="flex items-center justify-center gap-1.5">
                        <h1 className="text-xl sm:text-2xl font-black text-[#1E2328] tracking-tight">
                            {fullName}
                        </h1>
                        <BadgeCheck className="w-5 h-5 text-[#1E9444]" />
                    </div>
                    <p className="text-xs text-[#5A6270] font-bold mt-0.5">
                        {farmName}
                    </p>
                </div>

                <div className="flex items-center gap-2 pt-1 flex-wrap justify-center text-xs">
                    <span className="px-3 py-1 rounded-full bg-emerald-50 text-[#1E9444] border border-emerald-200 font-extrabold flex items-center gap-1">
                        <CheckCircle2 className="w-3.5 h-3.5 text-[#1E9444]" /> Verified Producer
                    </span>
                    <span className="px-3 py-1 rounded-full bg-amber-50 text-[#D88C0A] border border-amber-200 font-extrabold flex items-center gap-1">
                        <Award className="w-3.5 h-3.5 text-[#D88C0A]" /> 4 Years on Platform
                    </span>
                    <span className="px-3 py-1 rounded-full bg-blue-50 text-[#0B57D0] border border-blue-200 font-extrabold flex items-center gap-1">
                        <TrendingUp className="w-3.5 h-3.5 text-[#0B57D0]" /> ETB 120M Harvest Payouts
                    </span>
                </div>
            </div>

            {/* LIGHT GROUPED PROFILE CARDS */}
            <div className="mt-4 space-y-3">

                {/* GROUP 1: FARMER DETAILS */}
                <div className="bg-white rounded-2xl border border-gray-200/80 overflow-hidden shadow-2xs">
                    <div className="px-4 py-2.5 text-[11px] font-extrabold text-[#1E9444] uppercase tracking-wider bg-gray-50 border-b border-gray-100">
                        Farmer & Co-Op Details
                    </div>

                    <div className="divide-y divide-gray-100">

                        {/* Row: Full Name */}
                        <div className="px-4 py-3.5 flex items-center justify-between hover:bg-gray-50/80 transition-colors">
                            <div className="flex items-center gap-3.5">
                                <div className="w-9 h-9 rounded-full bg-emerald-50 text-[#1E9444] flex items-center justify-center shrink-0">
                                    <User className="w-4 h-4" />
                                </div>
                                <div>
                                    <span className="text-xs font-black text-[#1E2328] block">{fullName}</span>
                                    <span className="text-[11px] text-[#5A6270] font-medium">Full Name</span>
                                </div>
                            </div>
                        </div>

                        {/* Row: Farm Name */}
                        <div className="px-4 py-3.5 flex items-center justify-between hover:bg-gray-50/80 transition-colors">
                            <div className="flex items-center gap-3.5">
                                <div className="w-9 h-9 rounded-full bg-emerald-50 text-[#1E9444] flex items-center justify-center shrink-0">
                                    <Sprout className="w-4 h-4" />
                                </div>
                                <div>
                                    <span className="text-xs font-black text-[#1E2328] block">{farmName}</span>
                                    <span className="text-[11px] text-[#5A6270] font-medium">Farm / Co-Operative Name</span>
                                </div>
                            </div>
                        </div>

                        {/* Row: Phone Number */}
                        <div className="px-4 py-3.5 flex items-center justify-between hover:bg-gray-50/80 transition-colors cursor-pointer">
                            <div className="flex items-center gap-3.5">
                                <div className="w-9 h-9 rounded-full bg-emerald-50 text-[#1E9444] flex items-center justify-center shrink-0">
                                    <Phone className="w-4 h-4" />
                                </div>
                                <div>
                                    <span className="text-xs font-black text-[#1E2328] block">{phone}</span>
                                    <span className="text-[11px] text-[#5A6270] font-medium">Phone Number</span>
                                </div>
                            </div>
                        </div>

                        {/* Row: Region */}
                        <div className="px-4 py-3.5 flex items-center justify-between hover:bg-gray-50/80 transition-colors">
                            <div className="flex items-center gap-3.5">
                                <div className="w-9 h-9 rounded-full bg-blue-50 text-[#0B57D0] flex items-center justify-center shrink-0">
                                    <Globe className="w-4 h-4" />
                                </div>
                                <div>
                                    <span className="text-xs font-black text-[#1E2328] block">{region}</span>
                                    <span className="text-[11px] text-[#5A6270] font-medium">Region & Kebele Origin</span>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

                {/* GROUP 2: PLATFORM TRUST & HARVEST VOLUME */}
                <div className="bg-white rounded-2xl border border-gray-200/80 overflow-hidden shadow-2xs">
                    <div className="px-4 py-2.5 text-[11px] font-extrabold text-[#D88C0A] uppercase tracking-wider bg-gray-50 border-b border-gray-100 flex items-center gap-1.5">
                        <Shield className="w-3.5 h-3.5 text-[#D88C0A]" /> Platform Trust & Harvest Metrics
                    </div>

                    <div className="divide-y divide-gray-100">
                        {/* Row: 4 Years on Platform */}
                        <div className="px-4 py-3.5 flex items-center justify-between hover:bg-gray-50/80 transition-colors">
                            <div className="flex items-center gap-3.5">
                                <div className="w-9 h-9 rounded-full bg-amber-50 text-[#D88C0A] flex items-center justify-center shrink-0">
                                    <Calendar className="w-4 h-4" />
                                </div>
                                <div>
                                    <span className="text-xs font-black text-[#1E2328] block">4 Years on this Platform</span>
                                    <span className="text-[11px] text-[#5A6270] font-medium">Active Verified Producer since 2022 (Verified Kebele Certificate)</span>
                                </div>
                            </div>
                            <span className="px-2.5 py-0.5 rounded-lg bg-amber-50 text-[#D88C0A] text-[10px] font-extrabold border border-amber-200">
                                TRUSTED
                            </span>
                        </div>

                        {/* Row: Spent 120M Birr */}
                        <div className="px-4 py-3.5 flex items-center justify-between hover:bg-gray-50/80 transition-colors">
                            <div className="flex items-center gap-3.5">
                                <div className="w-9 h-9 rounded-full bg-emerald-50 text-[#1E9444] flex items-center justify-center shrink-0">
                                    <TrendingUp className="w-4 h-4" />
                                </div>
                                <div>
                                    <span className="text-xs font-black text-[#1E9444] block">ETB 120,000,000 Birr</span>
                                    <span className="text-[11px] text-[#5A6270] font-medium">Total Harvest Sales Transacted via Chapa Escrow Payouts</span>
                                </div>
                            </div>
                            <span className="px-2.5 py-0.5 rounded-lg bg-emerald-50 text-[#1E9444] text-[10px] font-extrabold border border-emerald-200">
                                TOP PRODUCER
                            </span>
                        </div>
                    </div>
                </div>

                {/* GROUP 3: PAYOUT BANK & MOBILE MONEY SETUP */}
                <div className="bg-white rounded-2xl border border-gray-200/80 overflow-hidden shadow-2xs">
                    <div className="px-4 py-2.5 text-[11px] font-extrabold text-[#0B57D0] uppercase tracking-wider bg-gray-50 border-b border-gray-100 flex items-center justify-between">
                        <span>Bank & Mobile Money Payout Account</span>
                        <span className="text-[10px] text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full font-bold">AUTOMATED SETTLEMENT</span>
                    </div>

                    <div className="divide-y divide-gray-100">
                        <div className="px-4 py-3.5 flex items-center justify-between hover:bg-gray-50/80 transition-colors">
                            <div className="flex items-center gap-3.5">
                                <div className="w-9 h-9 rounded-full bg-amber-50 text-amber-600 flex items-center justify-center shrink-0">
                                    <CreditCard className="w-4 h-4" />
                                </div>
                                <div>
                                    <span className="text-xs font-black text-[#1E2328] block">{paymentProvider}</span>
                                    <span className="text-[11px] text-[#5A6270] font-medium">Holder: {accountName} • Acc: {accountNumber}</span>
                                </div>
                            </div>
                        </div>

                        <div className="px-4 py-3.5 flex items-center justify-between hover:bg-gray-50/80 transition-colors">
                            <div className="flex items-center gap-3.5">
                                <div className="w-9 h-9 rounded-full bg-blue-50 text-[#0B57D0] flex items-center justify-center shrink-0">
                                    <Building2 className="w-4 h-4" />
                                </div>
                                <div>
                                    <span className="text-xs font-black text-[#1E2328] block">{bankBranch}</span>
                                    <span className="text-[11px] text-[#5A6270] font-medium">Settlement Branch Location</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            {/* LIGHT MODAL DIALOG: EDIT FARMER PROFILE & PAYOUTS */}
            {isEditModalOpen && (
                <div className="fixed inset-0 bg-black/50 backdrop-blur-xs flex items-center justify-center p-4 z-50 animate-fade-in">
                    <div className="bg-white border border-gray-200 rounded-3xl p-6 max-w-md w-full shadow-2xl space-y-5 text-[#1E2328] relative max-h-[90vh] overflow-y-auto">
                        <div className="flex items-center justify-between border-b border-gray-100 pb-3">
                            <div className="flex items-center gap-2.5">
                                <div className="w-8 h-8 rounded-full bg-[#1E9444] text-white flex items-center justify-center shrink-0">
                                    <Edit3 className="w-4 h-4" />
                                </div>
                                <div>
                                    <h3 className="text-sm font-black text-[#1E2328]">Edit Farmer Profile</h3>
                                    <p className="text-[11px] text-[#5A6270]">Update farmer details & payout options</p>
                                </div>
                            </div>
                            <button
                                type="button"
                                onClick={() => setIsEditModalOpen(false)}
                                className="text-gray-400 hover:text-gray-600 p-1 rounded-full hover:bg-gray-100 cursor-pointer"
                            >
                                <X className="w-4 h-4" />
                            </button>
                        </div>

                        <form onSubmit={handleFormSubmit} className="space-y-3.5 text-xs">
                            <div className="space-y-1">
                                <label className="text-[#1E2328] font-bold">Full Name</label>
                                <input
                                    type="text"
                                    value={modalFullName}
                                    onChange={(e) => setModalFullName(e.target.value)}
                                    className="w-full bg-[#F8F9FA] border border-gray-200 rounded-xl px-3.5 py-2.5 text-[#1E2328] font-bold focus:outline-none focus:border-[#1E9444]"
                                    required
                                />
                            </div>

                            <div className="space-y-1">
                                <label className="text-[#1E2328] font-bold">Farm / Co-Op Name</label>
                                <input
                                    type="text"
                                    value={modalFarmName}
                                    onChange={(e) => setModalFarmName(e.target.value)}
                                    className="w-full bg-[#F8F9FA] border border-gray-200 rounded-xl px-3.5 py-2.5 text-[#1E2328] font-bold focus:outline-none focus:border-[#1E9444]"
                                    required
                                />
                            </div>

                            <div className="space-y-1">
                                <label className="text-[#1E2328] font-bold">Phone Number</label>
                                <input
                                    type="text"
                                    value={modalPhone}
                                    onChange={(e) => setModalPhone(e.target.value)}
                                    className="w-full bg-[#F8F9FA] border border-gray-200 rounded-xl px-3.5 py-2.5 text-[#1E2328] font-bold focus:outline-none focus:border-[#1E9444]"
                                    required
                                />
                            </div>

                            <div className="space-y-1">
                                <label className="text-[#1E2328] font-bold">Region & Kebele</label>
                                <input
                                    type="text"
                                    value={modalRegion}
                                    onChange={(e) => setModalRegion(e.target.value)}
                                    className="w-full bg-[#F8F9FA] border border-gray-200 rounded-xl px-3.5 py-2.5 text-[#1E2328] font-bold focus:outline-none focus:border-[#1E9444]"
                                    required
                                />
                            </div>

                            <div className="pt-2 border-t border-gray-100 space-y-2">
                                <h4 className="font-extrabold text-[#1E9444]">Payout Bank Account</h4>

                                <div className="space-y-1">
                                    <label className="text-[#1E2328] font-bold">Bank / Mobile Money Provider</label>
                                    <select
                                        value={modalProvider}
                                        onChange={(e) => setModalProvider(e.target.value)}
                                        className="w-full bg-[#F8F9FA] border border-gray-200 rounded-xl px-3.5 py-2 text-[#1E2328] font-bold focus:outline-none focus:border-[#1E9444]"
                                    >
                                        <option value="Commercial Bank of Ethiopia (CBE)">Commercial Bank of Ethiopia (CBE)</option>
                                        <option value="Telebirr (Ethio Telecom Mobile Money)">Telebirr (Ethio Telecom)</option>
                                        <option value="Dashen Bank / Amole">Dashen Bank / Amole</option>
                                        <option value="Awash International Bank">Awash International Bank</option>
                                        <option value="Bank of Abyssinia">Bank of Abyssinia</option>
                                        <option value="Cooperative Bank of Oromia (CBO)">Cooperative Bank of Oromia (CBO)</option>
                                    </select>
                                </div>

                                <div className="space-y-1">
                                    <label className="text-[#1E2328] font-bold">Account Holder Name</label>
                                    <input
                                        type="text"
                                        value={modalAccountName}
                                        onChange={(e) => setModalAccountName(e.target.value)}
                                        className="w-full bg-[#F8F9FA] border border-gray-200 rounded-xl px-3.5 py-2 text-[#1E2328] font-bold focus:outline-none focus:border-[#1E9444]"
                                    />
                                </div>

                                <div className="space-y-1">
                                    <label className="text-[#1E2328] font-bold">Account Number / Telebirr Number</label>
                                    <input
                                        type="text"
                                        value={modalAccountNumber}
                                        onChange={(e) => setModalAccountNumber(e.target.value)}
                                        className="w-full bg-[#F8F9FA] border border-gray-200 rounded-xl px-3.5 py-2 text-[#1E2328] font-bold focus:outline-none focus:border-[#1E9444]"
                                    />
                                </div>
                            </div>

                            <div className="pt-3 border-t border-gray-100 flex justify-end gap-2">
                                <button
                                    type="button"
                                    onClick={() => setIsEditModalOpen(false)}
                                    className="px-4 py-2 rounded-xl bg-gray-100 text-gray-700 font-bold hover:bg-gray-200 cursor-pointer"
                                >
                                    Cancel
                                </button>
                                <button
                                    type="submit"
                                    disabled={isSubmitting}
                                    className="px-4 py-2 rounded-xl bg-[#1E9444] hover:bg-[#0F5C2A] text-white font-bold cursor-pointer shadow-xs disabled:opacity-50"
                                >
                                    {isSubmitting ? 'Saving...' : 'Save Updates'}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
};

// frontend/src/pages/farmer/FarmerProfile.vue
<template>
  <div class="w-full flex flex-col min-h-full pb-8 max-w-5xl mx-auto space-y-5">
    <!-- Top Header Banner -->
    <div class="bg-gradient-to-r from-[#062E15] via-[#0F5C2A] to-[#0B57D0] text-white p-6 rounded-3xl shadow-sm relative overflow-hidden flex flex-col sm:flex-row sm:items-center justify-between gap-4">
      <div class="absolute -top-10 -right-10 w-40 h-40 bg-[#E69500]/20 rounded-full blur-2xl pointer-events-none" />
      
      <div class="flex items-center gap-4 relative z-10">
        <!-- Interactive Avatar upload / display -->
        <div class="relative group cursor-pointer" @click="triggerPhotoUpload">
          <div v-if="customPhotoUrl || farmer?.avatar" class="w-16 h-16 rounded-full overflow-hidden border-2 border-white shadow-md">
            <img :src="customPhotoUrl || farmer?.avatar" alt="Profile" class="w-full h-full object-cover" />
          </div>
          <div v-else class="w-16 h-16 rounded-full bg-white/20 border-2 border-white flex items-center justify-center text-3xl font-black text-white shrink-0 shadow-md">
            {{ farmer?.name?.[0] || 'D' }}
          </div>
          <div class="absolute inset-0 bg-black/40 rounded-full opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center text-white">
            <Camera class="w-4 h-4" />
          </div>
        </div>
        <input type="file" ref="fileInput" accept="image/*" class="hidden" @change="handlePhotoChange" />

        <div>
          <div class="flex items-center gap-2 flex-wrap">
            <h1 class="text-xl sm:text-2xl font-black text-white tracking-tight">{{ farmer?.name || 'Dawit Bekele' }}</h1>
            <span class="px-2 py-0.5 rounded-full text-[10px] font-extrabold bg-amber-400 text-amber-950 flex items-center gap-1 shadow-2xs">
              <ShieldCheck class="w-3 h-3" />
              <span>Verified Producer</span>
            </span>
          </div>
          <p class="text-xs text-[#C3EFCF] mt-0.5 font-medium flex items-center gap-1.5 flex-wrap">
            <span>{{ farmer?.region || 'Sidama' }} Region Agricultural Member</span>
            <span>•</span>
            <span>{{ farmer?.phone || 'No phone set' }}</span>
          </p>
        </div>
      </div>

      <!-- Action Buttons -->
      <div class="flex items-center gap-2 relative z-10 shrink-0">
        <button @click="openEditModal" 
          class="px-4 py-2.5 bg-white/15 hover:bg-white/25 border border-white/30 text-white rounded-xl text-xs font-black transition-all flex items-center gap-1.5 cursor-pointer backdrop-blur-xs">
          <Edit3 class="w-4 h-4 text-amber-300" />
          <span>Edit Profile</span>
        </button>
        <button @click="logout" 
          class="px-4 py-2.5 bg-red-500/20 hover:bg-red-500/30 border border-red-300/40 text-red-100 rounded-xl text-xs font-black transition-all flex items-center gap-1.5 cursor-pointer">
          <LogOut class="w-4 h-4" />
          <span>Sign Out</span>
        </button>
      </div>
    </div>

    <!-- Success Toast Notification -->
    <div v-if="successMsg" class="p-3.5 bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-bold rounded-xl flex items-center justify-between">
      <div class="flex items-center gap-2">
        <CheckCircle2 class="w-4 h-4 text-emerald-600 shrink-0" />
        <span>{{ successMsg }}</span>
      </div>
      <button @click="successMsg = ''" class="text-emerald-700 hover:text-emerald-900 font-extrabold text-sm">&times;</button>
    </div>

    <!-- Producer Identity & Verification Grid -->
    <div class="bg-white border border-[#E2E4E7] rounded-2xl p-6 shadow-xs space-y-6">
      <div class="flex items-center justify-between border-b border-gray-100 pb-3">
        <h3 class="text-base font-black text-[#1E2328]">Producer Identity & Verification</h3>
        <span class="text-xs font-bold text-[#1E9444] bg-emerald-50 px-2.5 py-1 rounded-lg border border-emerald-200">
          Chapa Escrow Settlement Ready
        </span>
      </div>

      <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 text-xs">
        <div class="bg-[#F8F9FA] p-4 rounded-xl border border-[#E2E4E7]">
          <span class="text-[#5A6270] font-bold block mb-1">Full Registered Name</span>
          <span class="text-sm font-black text-[#1E2328]">{{ farmer?.name || 'Not set' }}</span>
        </div>

        <div class="bg-[#F8F9FA] p-4 rounded-xl border border-[#E2E4E7]">
          <span class="text-[#5A6270] font-bold block mb-1">Mobile Phone (SMS & Alerts)</span>
          <span class="text-sm font-black text-[#1E2328]">{{ farmer?.phone || 'Not set' }}</span>
        </div>

        <div class="bg-[#F8F9FA] p-4 rounded-xl border border-[#E2E4E7]">
          <span class="text-[#5A6270] font-bold block mb-1">Agricultural Region</span>
          <span class="text-sm font-black text-[#1E9444]">{{ farmer?.region || 'Sidama Region' }}</span>
        </div>

        <div class="bg-[#F8F9FA] p-4 rounded-xl border border-[#E2E4E7]">
          <span class="text-[#5A6270] font-bold block mb-1">Farm Size (Hectares)</span>
          <span class="text-sm font-black text-[#1E2328]">{{ farmer?.farmSize ? farmer.farmSize + ' Hectares' : 'Not specified' }}</span>
        </div>

        <div class="bg-[#F8F9FA] p-4 rounded-xl border border-[#E2E4E7]">
          <span class="text-[#5A6270] font-bold block mb-1">Primary Crops</span>
          <span class="text-sm font-black text-[#1E2328]">
            {{ Array.isArray(farmer?.crops) ? farmer.crops.join(', ') : (farmer?.crops || 'Not specified') }}
          </span>
        </div>

        <div class="bg-[#F8F9FA] p-4 rounded-xl border border-[#E2E4E7]">
          <span class="text-[#5A6270] font-bold block mb-1">Co-op Union Membership</span>
          <span class="text-sm font-black text-[#0B57D0]">{{ farmer?.union || 'Independent Producer' }}</span>
        </div>

        <div class="bg-[#F8F9FA] p-4 rounded-xl border border-[#E2E4E7] sm:col-span-2 md:col-span-3 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <span class="text-[#5A6270] font-bold block text-xs">Payout Account (Chapa / Bank / Telebirr)</span>
            <span class="text-sm font-black text-[#1E2328] flex items-center gap-2 mt-0.5">
              <span class="text-[#0B57D0] uppercase font-mono font-bold px-2 py-0.5 bg-blue-50 border border-blue-200 rounded-md text-xs">
                {{ farmer?.bank_code || farmer?.bank_name || 'CBE' }}
              </span>
              <span>{{ farmer?.account_number ? ('******' + farmer.account_number.slice(-4)) : 'Not configured' }}</span>
              <span v-if="farmer?.account_name" class="text-xs font-semibold text-gray-500">({{ farmer.account_name }})</span>
            </span>
          </div>
          <button @click="openEditModal" class="text-xs font-black text-[#0B57D0] hover:underline self-start sm:self-auto cursor-pointer">
            Update Payout Account &rarr;
          </button>
        </div>
      </div>
    </div>

    <!-- Edit Profile Modal with Tabbed Sections -->
    <div v-if="showEditModal" class="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4">
      <div class="max-w-lg w-full bg-white rounded-3xl p-6 shadow-2xl space-y-5 text-[#1E2328] border border-gray-100 animate-in fade-in zoom-in-95 duration-150">
        <!-- Modal Header -->
        <div class="flex items-center justify-between border-b border-gray-100 pb-3">
          <div class="flex items-center gap-2.5">
            <div class="p-2 bg-emerald-50 text-[#1E9444] rounded-xl">
              <UserCheck class="w-5 h-5" />
            </div>
            <div>
              <h3 class="text-base font-black text-[#1E2328]">Edit Farmer Profile</h3>
              <p class="text-[11px] text-[#5A6270]">Manage producer identity, farm size, & payout setup</p>
            </div>
          </div>
          <button @click="showEditModal = false" class="p-1.5 text-gray-400 hover:text-gray-700 hover:bg-gray-100 rounded-xl transition-colors">
            <X class="w-5 h-5" />
          </button>
        </div>

        <!-- Navigation Tabs -->
        <div class="flex border-b border-gray-100 text-xs font-bold gap-4">
          <button 
            @click="activeTab = 'credentials'" 
            :class="[
              'pb-2.5 border-b-2 transition-colors flex items-center gap-1.5 cursor-pointer',
              activeTab === 'credentials' ? 'border-[#1E9444] text-[#1E9444]' : 'border-transparent text-gray-500 hover:text-gray-800'
            ]"
          >
            <User class="w-3.5 h-3.5" />
            <span>Credentials & Password</span>
          </button>
          <button 
            @click="activeTab = 'farm'" 
            :class="[
              'pb-2.5 border-b-2 transition-colors flex items-center gap-1.5 cursor-pointer',
              activeTab === 'farm' ? 'border-[#1E9444] text-[#1E9444]' : 'border-transparent text-gray-500 hover:text-gray-800'
            ]"
          >
            <Sprout class="w-3.5 h-3.5" />
            <span>Farm & Payout Account</span>
          </button>
        </div>

        <!-- Error Alert -->
        <div v-if="modalError" class="p-3 bg-red-50 border border-red-200 text-red-700 text-xs font-bold rounded-xl flex items-center gap-2">
          <AlertCircle class="w-4 h-4 text-red-600 shrink-0" />
          <span>{{ modalError }}</span>
        </div>

        <!-- Tab 1: Credentials & Security -->
        <div v-if="activeTab === 'credentials'" class="space-y-4 text-xs">
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label class="block font-extrabold text-[#1E2328] mb-1">First Name</label>
              <input type="text" v-model="form.first_name" placeholder="First Name"
                class="w-full px-3.5 py-2.5 bg-gray-50 border border-gray-200 rounded-xl font-bold text-xs focus:outline-none focus:border-[#1E9444] focus:bg-white transition-all" />
            </div>
            <div>
              <label class="block font-extrabold text-[#1E2328] mb-1">Second Name / Family</label>
              <input type="text" v-model="form.second_name" placeholder="Second Name"
                class="w-full px-3.5 py-2.5 bg-gray-50 border border-gray-200 rounded-xl font-bold text-xs focus:outline-none focus:border-[#1E9444] focus:bg-white transition-all" />
            </div>
          </div>

          <div>
            <label class="block font-extrabold text-[#1E2328] mb-1">Mobile Phone Number</label>
            <div class="relative">
              <Phone class="w-4 h-4 text-gray-400 absolute left-3 top-3" />
              <input type="text" v-model="form.phone" placeholder="+251 912 345 678"
                class="w-full pl-9 pr-3.5 py-2.5 bg-gray-50 border border-gray-200 rounded-xl font-bold text-xs focus:outline-none focus:border-[#1E9444] focus:bg-white transition-all" />
            </div>
          </div>

          <div class="pt-2 border-t border-gray-100">
            <h4 class="font-black text-[#1E2328] mb-2 flex items-center gap-1.5">
              <Key class="w-3.5 h-3.5 text-[#1E9444]" />
              <span>Change Password (Optional)</span>
            </h4>
            <div class="space-y-2.5">
              <div>
                <label class="block text-[11px] font-bold text-gray-600 mb-1">Current Password</label>
                <input type="password" v-model="form.current_password" placeholder="Enter current password if changing"
                  class="w-full px-3.5 py-2 bg-gray-50 border border-gray-200 rounded-xl font-semibold text-xs focus:outline-none focus:border-[#1E9444] focus:bg-white transition-all" />
              </div>
              <div class="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                <div>
                  <label class="block text-[11px] font-bold text-gray-600 mb-1">New Password</label>
                  <input type="password" v-model="form.new_password" placeholder="At least 6 chars"
                    class="w-full px-3.5 py-2 bg-gray-50 border border-gray-200 rounded-xl font-semibold text-xs focus:outline-none focus:border-[#1E9444] focus:bg-white transition-all" />
                </div>
                <div>
                  <label class="block text-[11px] font-bold text-gray-600 mb-1">Confirm New Password</label>
                  <input type="password" v-model="form.confirm_password" placeholder="Re-type new password"
                    class="w-full px-3.5 py-2 bg-gray-50 border border-gray-200 rounded-xl font-semibold text-xs focus:outline-none focus:border-[#1E9444] focus:bg-white transition-all" />
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Tab 2: Farm & Payout Details -->
        <div v-if="activeTab === 'farm'" class="space-y-3.5 text-xs">
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label class="block font-extrabold text-[#1E2328] mb-1">Agricultural Region</label>
              <select v-model="form.region" class="w-full px-3.5 py-2.5 bg-gray-50 border border-gray-200 rounded-xl font-bold text-xs focus:outline-none focus:border-[#1E9444] focus:bg-white transition-all">
                <option value="Sidama">Sidama Region</option>
                <option value="Oromia">Oromia Region</option>
                <option value="Amhara">Amhara Region</option>
                <option value="SNNPR">SNNPR Region</option>
                <option value="South Ethiopia">South Ethiopia</option>
                <option value="Tigray">Tigray Region</option>
                <option value="Harari">Harari Region</option>
              </select>
            </div>
            <div>
              <label class="block font-extrabold text-[#1E2328] mb-1">Farm Size (Hectares)</label>
              <input type="number" step="0.5" v-model="form.farmSize" placeholder="e.g. 14.5"
                class="w-full px-3.5 py-2.5 bg-gray-50 border border-gray-200 rounded-xl font-bold text-xs focus:outline-none focus:border-[#1E9444] focus:bg-white transition-all" />
            </div>
          </div>

          <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label class="block font-extrabold text-[#1E2328] mb-1">Primary Crops (Comma separated)</label>
              <input type="text" v-model="form.crops" placeholder="e.g. Coffee, Teff, Spices"
                class="w-full px-3.5 py-2.5 bg-gray-50 border border-gray-200 rounded-xl font-bold text-xs focus:outline-none focus:border-[#1E9444] focus:bg-white transition-all" />
            </div>
            <div>
              <label class="block font-extrabold text-[#1E2328] mb-1">Co-op Union Membership</label>
              <input type="text" v-model="form.union" placeholder="e.g. Sidama Farmers Union"
                class="w-full px-3.5 py-2.5 bg-gray-50 border border-gray-200 rounded-xl font-bold text-xs focus:outline-none focus:border-[#1E9444] focus:bg-white transition-all" />
            </div>
          </div>

          <div class="pt-2 border-t border-gray-100">
            <h4 class="font-black text-[#1E2328] mb-2 flex items-center gap-1.5">
              <CreditCard class="w-3.5 h-3.5 text-[#1E9444]" />
              <span>Chapa Escrow Payout Account</span>
            </h4>
            <div class="space-y-2.5">
              <div>
                <label class="block text-[11px] font-bold text-gray-600 mb-1">Bank / Mobile Money Provider</label>
                <select v-model="form.bank_code" class="w-full px-3.5 py-2 bg-gray-50 border border-gray-200 rounded-xl font-bold text-xs focus:outline-none focus:border-[#1E9444] focus:bg-white transition-all">
                  <option value="CBE">Commercial Bank of Ethiopia (CBE)</option>
                  <option value="TELEBIRR">Telebirr Mobile Money</option>
                  <option value="DASHEN">Dashen Bank</option>
                  <option value="AWASH">Awash Bank</option>
                  <option value="ABYSSINIA">Bank of Abyssinia</option>
                  <option value="COOP">Cooperative Bank of Oromia</option>
                </select>
              </div>
              <div class="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                <div>
                  <label class="block text-[11px] font-bold text-gray-600 mb-1">Account Number / Phone</label>
                  <input type="text" v-model="form.account_number" placeholder="1000..."
                    class="w-full px-3.5 py-2 bg-gray-50 border border-gray-200 rounded-xl font-mono font-bold text-xs focus:outline-none focus:border-[#1E9444] focus:bg-white transition-all" />
                </div>
                <div>
                  <label class="block text-[11px] font-bold text-gray-600 mb-1">Account Holder Name</label>
                  <input type="text" v-model="form.account_name" placeholder="Full name as on account"
                    class="w-full px-3.5 py-2 bg-gray-50 border border-gray-200 rounded-xl font-semibold text-xs focus:outline-none focus:border-[#1E9444] focus:bg-white transition-all" />
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Modal Actions -->
        <div class="flex gap-2.5 pt-3 border-t border-gray-100">
          <button @click="showEditModal = false" class="flex-1 py-2.5 border border-gray-200 rounded-xl font-bold text-xs text-gray-700 hover:bg-gray-50 transition-colors">
            Cancel
          </button>
          <button @click="saveProfile" :disabled="isSaving"
            class="flex-1 py-2.5 bg-[#1E9444] hover:bg-[#167033] text-white rounded-xl font-bold text-xs transition-colors shadow-sm flex items-center justify-center gap-2 disabled:opacity-50 cursor-pointer">
            <Loader2 v-if="isSaving" class="w-4 h-4 animate-spin" />
            <span>Save Profile</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, computed } from 'vue'
import { 
  ShieldCheck, Phone, Edit3, LogOut, Camera, X, User, Key, 
  UserCheck, AlertCircle, CheckCircle2, Loader2, Sprout, CreditCard 
} from 'lucide-vue-next'
import { useAuth } from '@/composables/useAuth'
import { api } from '@/services/api'

const { user, logout, updateUserProfile } = useAuth()
const farmer = computed(() => user.value)

const showEditModal = ref(false)
const activeTab = ref('credentials')
const fileInput = ref(null)
const customPhotoUrl = ref(null)
const modalError = ref('')
const successMsg = ref('')
const isSaving = ref(false)

const form = reactive({
  first_name: '',
  second_name: '',
  phone: '',
  current_password: '',
  new_password: '',
  confirm_password: '',
  region: '',
  farmSize: '',
  crops: '',
  union: '',
  bank_code: '',
  bank_name: '',
  account_number: '',
  account_name: ''
})

const openEditModal = () => {
  modalError.value = ''
  const nameParts = (user.value?.name || '').split(' ')
  form.first_name = user.value?.first_name || nameParts[0] || ''
  form.second_name = user.value?.second_name || nameParts.slice(1).join(' ') || ''
  form.phone = user.value?.phone || ''
  form.current_password = ''
  form.new_password = ''
  form.confirm_password = ''
  form.region = user.value?.region || 'Sidama'
  form.farmSize = user.value?.farmSize || ''
  form.crops = Array.isArray(user.value?.crops) ? user.value.crops.join(', ') : (user.value?.crops || '')
  form.union = user.value?.union || ''
  form.bank_code = user.value?.bank_code || 'CBE'
  form.bank_name = user.value?.bank_name || 'Commercial Bank of Ethiopia'
  form.account_number = user.value?.account_number || ''
  form.account_name = user.value?.account_name || user.value?.name || ''
  activeTab.value = 'credentials'
  showEditModal.value = true
}

const triggerPhotoUpload = () => {
  if (fileInput.value) {
    fileInput.value.click()
  }
}

const handlePhotoChange = async (e) => {
  const file = e.target.files?.[0]
  if (file) {
    customPhotoUrl.value = URL.createObjectURL(file)
    try {
      const formData = new FormData()
      formData.append('profile_photo', file)
      await api.updateProfile(formData)
      successMsg.value = 'Profile photo updated successfully!'
    } catch {
      // offline fallback
    }
  }
}

const saveProfile = async () => {
  modalError.value = ''

  if (form.new_password) {
    if (!form.current_password) {
      modalError.value = 'Please enter your current password to change password.'
      activeTab.value = 'credentials'
      return
    }
    if (form.new_password.length < 6) {
      modalError.value = 'New password must be at least 6 characters long.'
      activeTab.value = 'credentials'
      return
    }
    if (form.new_password !== form.confirm_password) {
      modalError.value = 'New password and confirmation do not match.'
      activeTab.value = 'credentials'
      return
    }
  }

  isSaving.value = true

  try {
    await updateUserProfile({
      first_name: form.first_name,
      second_name: form.second_name,
      phone: form.phone,
      current_password: form.current_password || undefined,
      new_password: form.new_password || undefined,
      region: form.region,
      farmSize: form.farmSize,
      crops: form.crops,
      union: form.union,
      bank_code: form.bank_code,
      bank_name: form.bank_name,
      account_number: form.account_number,
      account_name: form.account_name,
    })

    showEditModal.value = false
    successMsg.value = 'Profile updated successfully!'
    setTimeout(() => {
      successMsg.value = ''
    }, 4000)
  } catch (err) {
    modalError.value = err.message || 'Failed to save profile changes. Please try again.'
  } finally {
    isSaving.value = false
  }
}
</script>
